<?php
return array (
  'article' => '文章',
  'block' => '碎片',
  'block_history' => '碎片历史',
  'block_type' => '碎片类型',
  'brand' => '品牌',
  'brand_type' => '品牌分类',
  'cache' => '缓存',
  'channel' => '频道',
  'focus' => '首焦',
  'goods' => '商品',
  'goods_type' => '商品分类',
  'link' => '友情链接',
  'member' => '会员',
  'menu' => '菜单',
  'model' => '模型',
  'module' => '模块',
  'point' => '积分',
  'point_set' => '积分设置',
  'position' => '推荐位',
  'position_data' => '推荐位数据',
  'prize' => '奖品',
  'prize_set' => '抽奖设置',
  'release_point' => '相关发布点',
  'seckill' => '秒杀',
  'shop' => '店铺',
  'site' => '站点配置',
  'special' => '专题',
  'weblink' => '网页链接',
  'weblink_type' => '网页链接分类',
  'site_config' => '网站信息',
);
?>